version: '3.8'
services: 

  nginx:
    container_name: loadbalancer
    build: 
      context: .
      dockerfile: dockerfile.nginx
    depends_on:
      - node-app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    container_name: node-app
    build: 
      context: .
      dockerfile: dockerfile.node
    environment:
      - PORT=8080
    depends_on:
      - mongo_one
      - mongo_two
      - mongo_three
      - redis_one
      - redis_two

  mongo_one:
    container_name: mongo1
    image: mongo
    command: mongod --replSet my-mongo-set
    ports:
      - 30001:27017
    volumes: 
      - ./mongo/mongo_one/data:/data/db
    depends_on:
      - mongo_two
      - mongo_three
  mongo_two:
    container_name: mongo2
    image: mongo
    command: mongod --replSet my-mongo-set
    ports:
      - 30002:27017
    volumes: 
      - ./mongo/mongo_two/data:/data/db
  mongo_three:
    container_name: mongo3
    image: mongo
    command: mongod --replSet my-mongo-set
    ports:
      - 30003:27017
    volumes: 
      - ./mongo/mongo_three/data:/data/db
      
  redis_one:
    container_name: cashing_layer
    image: redis

  redis_two:
    container_name: session
    image: redis

# volumes:
#   mongo-db:


